matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      cache:
        directories:
        - $HOME/.minikube
        - $HOME/.kube
        - $HOME/.local/bin
        - .git
        - /usr/local
      env:
        - MINIKUBE_MEMORY=7777
        - MINIKUBE_CPU=4
        - MINIKUBE_DRIVER=none
        - HELM_INSTALL_DIR=$HOME/.local/bin
        - NVM_DIR="$HOME/.nvm"

language: bash


before_install:
# install nsenter which is required for port forwarding

script:
  - echo 'Add tests here'
