import { sha256, stringifyCanonical } from "../blockchain/crypto.js";

/**
 * Statutory Form 990 & Corporate Annual Report Exporter for LegitBlock.
 * Extracts governance minutes, officer elections, bylaw amendments, and financial resolutions
 * from the blockchain to produce statutory annual filing schedules (IRS Form 990 & Delaware Franchise Tax).
 */

export class StatutoryTaxExporter {
  /**
   * Export an IRS Form 990 Schedule / Part VI Governance Report
   * @param {import("../blockchain/blockchain.js").Blockchain} blockchain
   * @param {number} fiscalYear - e.g. 2026
   * @returns {object} Form 990 Part VI data structure
   */
  static exportForm990GovernancePacket(blockchain, fiscalYear) {
    const yearStart = new Date(`${fiscalYear}-01-01T00:00:00.000Z`).getTime();
    const yearEnd = new Date(`${fiscalYear}-12-31T23:59:59.999Z`).getTime();

    const org = blockchain.organization || {};
    const chain = blockchain.chain || [];

    // Filter blocks within fiscal year
    const yearBlocks = chain.filter(b => {
      const blockTime = new Date(b.timestamp).getTime();
      return blockTime >= yearStart && blockTime <= yearEnd;
    });

    const officers = [];
    const votingMembers = new Set();
    const bylawAmendments = [];
    const significantDecisions = [];

    // Current members
    const members = blockchain.getMembers ? blockchain.getMembers() : (org.foundingMembers || []);
    for (const m of members) {
      if (m.role?.toLowerCase().includes("director") || m.role?.toLowerCase().includes("officer") || m.role?.toLowerCase().includes("president") || m.role?.toLowerCase().includes("treasurer")) {
        officers.push({
          name: m.name,
          role: m.role,
          id: m.id
        });
      }
      votingMembers.add(m.id);
    }

    for (const b of yearBlocks) {
      const isDocAmend = b.type === "DOCUMENT_AMEND" || b.data?.action === "AMEND" || b.data?.type === "DOCUMENT_AMENDMENT";
      const isVoteTally = b.type === "VOTE_TALLY" || b.data?.action === "VOTE_EXECUTE";
      const title = b.data?.title || b.data?.documentTitle || "";

      if (isDocAmend) {
        if (title.toLowerCase().includes("bylaw") || title.toLowerCase().includes("charter") || title.toLowerCase().includes("constitution") || title.toLowerCase().includes("policy")) {
          bylawAmendments.push({
            blockIndex: b.index,
            date: b.timestamp,
            title,
            hash: b.hash
          });
        }
        significantDecisions.push({
          blockIndex: b.index,
          date: b.timestamp,
          action: "DOCUMENT_AMENDMENT",
          description: b.data?.notes || title || "Document amendment"
        });
      } else if (isVoteTally) {
        significantDecisions.push({
          blockIndex: b.index,
          date: b.timestamp,
          action: "VOTE_EXECUTION",
          description: b.data?.title || "Executed governance vote"
        });
      }
    }

    const report = {
      organizationName: org.name || "LegitBlock Organization",
      jurisdiction: org.jurisdiction || "Delaware",
      fiscalYear,
      formType: "IRS Form 990 (Part VI - Governance, Management, and Disclosure)",
      line1a_votingMembersCount: votingMembers.size,
      line1b_independentDirectorsCount: officers.filter(o => o.role.toLowerCase().includes("independent") || o.role.toLowerCase().includes("director")).length,
      line2_officersAndDirectors: officers,
      line4_significantChangesToOrganizingDocs: bylawAmendments.length > 0,
      bylawAmendmentsSummary: bylawAmendments,
      line8_contemporaneousDocumentationOfMeetings: true,
      documentedResolutionsCount: significantDecisions.length,
      resolutionsSummary: significantDecisions,
      blockchainAuditSeal: sha256(stringifyCanonical({
        fiscalYear,
        blocksCount: yearBlocks.length,
        votingMembersCount: votingMembers.size,
        bylawAmendmentsCount: bylawAmendments.length
      })),
      generatedAt: new Date().toISOString()
    };

    return report;
  }

  /**
   * Export Markdown formatted Schedule O attachment for filing
   * @param {object} packet - Generated by exportForm990GovernancePacket
   * @returns {string} Markdown document
   */
  static formatScheduleOMarkdown(packet) {
    let md = `# SCHEDULE O (Form 990) Supplemental Information\n\n`;
    md += `**Organization**: ${packet.organizationName}\n`;
    md += `**Fiscal Year**: ${packet.fiscalYear}\n`;
    md += `**Blockchain Audit Seal**: \`${packet.blockchainAuditSeal}\`\n\n`;
    md += `---\n\n`;
    md += `### Part VI, Line 1a & 1b: Governing Body Composition\n`;
    md += `- Total Voting Members: **${packet.line1a_votingMembersCount}**\n`;
    md += `- Independent Directors: **${packet.line1b_independentDirectorsCount}**\n\n`;
    md += `### Part VI, Line 2: Officers and Key Management\n`;
    for (const o of packet.line2_officersAndDirectors) {
      md += `- **${o.name}** — ${o.role} (Member ID: \`${o.id}\`)\n`;
    }
    md += `\n### Part VI, Line 4: Material Changes to Governing Documents\n`;
    if (packet.line4_significantChangesToOrganizingDocs) {
      md += `During fiscal year ${packet.fiscalYear}, the organization ratified the following governing document amendments on the blockchain ledger:\n\n`;
      for (const a of packet.bylawAmendmentsSummary) {
        md += `1. **${a.title}** (Ratified: ${new Date(a.date).toLocaleDateString()}, Block #${a.blockIndex}, Hash: \`${a.hash.substring(0, 16)}...\`)\n`;
      }
    } else {
      md += `No material changes were made to organizing documents during fiscal year ${packet.fiscalYear}.\n`;
    }
    md += `\n### Part VI, Line 8: Contemporaneous Meeting Documentation\n`;
    md += `All actions, shareholder resolutions, and board votes are recorded immutably on the organization's blockchain ledger satisfying DGCL § 224 and IRS contemporaneous record-keeping requirements.\n`;
    md += `Total ratified resolutions in fiscal year: **${packet.documentedResolutionsCount}**.\n`;
    return md;
  }
}
