name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js (26.x)
        uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: pnpm

      - name: Setup Pages Configuration
        id: pages
        uses: actions/configure-pages@v6

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro Static Site
        run: pnpm build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./apps/legitblock-github.io/out


  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/neo1'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
